//! MQTT 5.0 Reason Codes
//!
//! The CONNACK, PUBACK, PUBREC, PUBREL, PUBCOMP, DISCONNECT and AUTH Control Packets
//! have a single Reason Code as part of the Variable Header.
//! Each of these Reason Codes is a subset of the full set of Reason Codes defined in this module.

pub const SUCCESS: u8 = 0; // CONNACK, PUBACK, PUBREC, PUBREL, PUBCOMP, UNSUBACK, AUTH
pub const NORMAL_DISCONNECTION: u8 = 0; // DISCONNECT
pub const GRANTED_QOS_0: u8 = 0; // SUBACK
pub const GRANTED_QOS_1: u8 = 1; // SUBACK
pub const GRANTED_QOS_2: u8 = 2; // SUBACK
pub const DISCONNECT_WITH_WILL_MESSAGE: u8 = 4; // DISCONNECT
pub const NO_MATCHING_SUBSCRIBERS: u8 = 16; // PUBACK, PUBREC
pub const NO_SUBSCRIPTION_EXISTED: u8 = 17; // UNSUBACK
pub const CONTINUE_AUTHENTICATION: u8 = 24; // AUTH
pub const RE_AUTHENTICATE: u8 = 25; // AUTH
pub const UNSPECIFIED_ERROR: u8 = 128; // CONNACK, PUBACK, PUBREC, SUBACK, UNSUBACK, DISCONNECT
pub const MALFORMED_PACKET: u8 = 129; // CONNACK, DISCONNECT
pub const PROTOCOL_ERROR: u8 = 130; // CONNACK, DISCONNECT
pub const IMPLEMENTATION_SPECIFIC_ERROR: u8 = 131; // CONNACK, PUBACK, PUBREC, SUBACK, UNSUBACK, DISCONNECT
pub const UNSUPPORTED_PROTOCOL_VERSION: u8 = 132; // CONNACK
pub const CLIENT_IDENTIFIER_NOT_VALID: u8 = 133; // CONNACK
pub const BAD_USER_NAME_OR_PASSWORD: u8 = 134; // CONNACK
pub const NOT_AUTHORIZED: u8 = 135; // CONNACK, PUBACK, PUBREC, SUBACK, UNSUBACK, DISCONNECT
pub const SERVER_UNAVAILABLE: u8 = 136; // CONNACK
pub const SERVER_BUSY: u8 = 137; // CONNACK, DISCONNECT
pub const BANNED: u8 = 138; // CONNACK
pub const SERVER_SHUTTING_DOWN: u8 = 139; // DISCONNECT
pub const BAD_AUTHENTICATION_METHOD: u8 = 140; // CONNACK, DISCONNECT
pub const KEEP_ALIVE_TIMEOUT: u8 = 141; // DISCONNECT
pub const SESSION_TAKEN_OVER: u8 = 142; // DISCONNECT
pub const TOPIC_FILTER_INVALID: u8 = 143; // SUBACK, UNSUBACK, DISCONNECT
pub const TOPIC_NAME_INVALID: u8 = 144; // CONNACK, PUBACK, PUBREC, DISCONNECT
pub const PACKET_IDENTIFIER_IN_USE: u8 = 145; // PUBACK, PUBREC, SUBACK, UNSUBACK
pub const PACKET_IDENTIFIER_NOT_FOUND: u8 = 146; // PUBREL, PUBCOMP
pub const RECEIVE_MAXIMUM_EXCEEDED: u8 = 147; // DISCONNECT
pub const TOPIC_ALIAS_INVALID: u8 = 148; // DISCONNECT
pub const PACKET_TOO_LARGE: u8 = 149; // CONNACK, DISCONNECT
pub const MESSAGE_RATE_TOO_HIGH: u8 = 150; // DISCONNECT
pub const QUOTA_EXCEEDED: u8 = 151; // CONNACK, PUBACK, PUBREC, SUBACK, DISCONNECT
pub const ADMINISTRATIVE_ACTION: u8 = 152; // DISCONNECT
pub const PAYLOAD_FORMAT_INVALID: u8 = 153; // CONNACK, PUBACK, PUBREC, DISCONNECT
pub const RETAIN_NOT_SUPPORTED: u8 = 154; // CONNACK, DISCONNECT
pub const QOS_NOT_SUPPORTED: u8 = 155; // CONNACK, DISCONNECT
pub const USE_ANOTHER_SERVER: u8 = 156; // CONNACK, DISCONNECT
pub const SERVER_MOVED: u8 = 157; // CONNACK, DISCONNECT
pub const SHARED_SUBSCRIPTIONS_NOT_SUPPORTED: u8 = 158; // SUBACK, DISCONNECT
pub const CONNECTION_RATE_EXCEEDED: u8 = 159; // CONNACK, DISCONNECT
pub const MAXIMUM_CONNECT_TIME: u8 = 160; // DISCONNECT
pub const SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED: u8 = 161; // SUBACK, DISCONNECT
pub const WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED: u8 = 162; // SUBACK, DISCONNECT
